### ISSUE TITLE
Fails on Debian 7

### ISSUE THREAD

**Issue by 0x27** [pycepa/pycepa#11]
Traceback below, need to debug. Any ideas, @entr0pist ?

```
[root@i.broke.science:~/pytor]# uname -a
Linux i.broke.science 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux
[root@i.broke.science:~/pytor]# python -V
Python 2.7.3
[root@i.broke.science:~/pytor]# python tor.py start
2015-08-10 10:41:47,992:core.daemon: starting server..
2015-08-10 10:41:47,995:core.events: registering 'module_loaded_Select' in /root/pytor/core/module_driver.py:38:load_module
2015-08-10 10:41:47,996:core.events: registering 'tor_get_router' in /root/pytor/modules/Tor/DirServ.py:36:module_load
2015-08-10 10:41:47,996:core.events: raising 'module_loaded_DirServ' in /root/pytor/core/module_driver.py:39:load_module
2015-08-10 10:41:48,923:core.events: registering 'tor_init_router' in /root/pytor/modules/Tor/Router.py:269:module_load
2015-08-10 10:41:48,924:core.events: raising 'module_loaded_Router' in /root/pytor/core/module_driver.py:39:load_module
2015-08-10 10:41:48,924:modules.Tor: initializing Tor.
2015-08-10 10:41:48,924:core.events: registering 'tor_got_md_['Exit', 'Stable', 'Fast']' in /root/pytor/modules/Tor/__init__.py:17:module_load
2015-08-10 10:41:48,924:core.events: raising 'tor_get_router' in /root/pytor/modules/Tor/__init__.py:18:module_load
2015-08-10 10:41:48,924:modules.Tor.DirServ: requesting consensus from 86.59.21.38
2015-08-10 10:41:48,925:core.events: raising 'http_get' in /root/pytor/modules/Tor/DirServ.py:76:retrieve_consensus
2015-08-10 10:41:48,925:core.daemon: server boot failed: 'NoneType' object has no attribute 'register_local'
Traceback (most recent call last):
  File "/root/pytor/core/daemon.py", line 46, in start
    modules.load_all()
  File "/root/pytor/core/module_driver.py", line 26, in load_all
    self.load_module(module_name)
  File "/root/pytor/core/module_driver.py", line 39, in load_module
    self.modules[module_name].init_module()
  File "/root/pytor/core/Module.py", line 35, in init_module
    self.module_load()
  File "/root/pytor/modules/Tor/__init__.py", line 18, in module_load
    self.trigger('tor_get_router', self.guard_node)
  File "/root/pytor/core/Module.py", line 58, in trigger
    return self.events.trigger(event, *args, **kwargs)
  File "/root/pytor/core/events.py", line 75, in trigger
    ret = function(*args, **kwargs)
  File "/root/pytor/modules/Tor/DirServ.py", line 42, in get_router
    self.retrieve_consensus()
  File "/root/pytor/modules/Tor/DirServ.py", line 77, in retrieve_consensus
    request.register_local('chunk', self.chunk)
AttributeError: 'NoneType' object has no attribute 'register_local'
[root@i.broke.science:~/pytor]# 
```

**Comment by 0x27** [comment]
Update: Wierdly, it works just fine on Debian 8 (Jessie).

```
hack@theplanet:~/pytor$ uname -a
Linux theplanet 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u2 (2015-07-17) x86_64 GNU/Linux
hack@theplanet:~/pytor$ python -V
Python 2.7.9
hack@theplanet:~/pytor$ 
```

**Comment by entr0pist** [comment]
945c8ff should fix this, can you confirm @0x27?

**Comment by 0x27** [comment]
Seems we still have the same issue. With a fresh git pull on that box I get the same traceback. Will give you a shell on it so you can test it. I also reverted to 945c8ff to test, issue still there.

```
[root@i.broke.science:~/pycepa]# git show
commit a2447d0a3311a619fcdfb2798a64958d4035e153
Author: entr0pist <entr0pist@users.noreply.github.com>
Date:   Tue Aug 11 05:47:22 2015 +0000

    Small performance tweak.

diff --git a/core/events.py b/core/events.py
index ab1480f..624f6fb 100644
--- a/core/events.py
+++ b/core/events.py
@@ -86,6 +86,10 @@ class Events(object):
         return ret

     def do_trace(self):
+        # trace is expensive so only do it when we need it
+        if log.level <= logging.DEBUG:
+            return ''
+
         trace = traceback.extract_stack()[::-1]
         for t in trace:
             if os.path.basename(t[0]) in [ 'events.py', 'Module.py', 'LocalModule.py' ]:
[root@i.broke.science:~/pycepa]# ./tor.py start
2015-08-11 08:23:50,988:core.daemon: starting server..
2015-08-11 08:23:50,991:core.events: registering 'module_loaded_Select' in 
2015-08-11 08:23:50,992:core.events: registering 'tor_get_router' in 
2015-08-11 08:23:50,992:core.events: raising 'module_loaded_DirServ' in 
2015-08-11 08:23:51,631:core.events: registering 'tor_init_router' in 
2015-08-11 08:23:51,631:core.events: raising 'module_loaded_Router' in 
2015-08-11 08:23:51,631:modules.Tor: initializing Tor.
2015-08-11 08:23:51,631:core.events: registering 'tor_got_md_['Guard', 'Stable', 'Fast', 'Valid', 'Running']' in 
2015-08-11 08:23:51,631:core.events: raising 'tor_get_router' in 
2015-08-11 08:23:51,632:modules.Tor.DirServ: requesting consensus from 86.59.21.38
2015-08-11 08:23:51,632:core.events: raising 'http_get' in 
2015-08-11 08:23:51,632:core.daemon: server boot failed: 'NoneType' object has no attribute 'register_local'
Traceback (most recent call last):
  File "/root/pycepa/core/daemon.py", line 46, in start
    modules.load_all()
  File "/root/pycepa/core/module_driver.py", line 26, in load_all
    self.load_module(module_name)
  File "/root/pycepa/core/module_driver.py", line 39, in load_module
    self.modules[module_name].init_module()
  File "/root/pycepa/core/Module.py", line 35, in init_module
    self.module_load()
  File "/root/pycepa/modules/Tor/__init__.py", line 18, in module_load
    self.trigger_avail('tor_get_router', self.guard_node)
  File "/root/pycepa/core/Module.py", line 61, in trigger_avail
    return self.events.trigger_avail(event, *args, **kwargs)
  File "/root/pycepa/core/events.py", line 61, in trigger_avail
    self.trigger(event, *args, **kwargs)
  File "/root/pycepa/core/events.py", line 75, in trigger
    ret = function(*args, **kwargs)
  File "/root/pycepa/modules/Tor/DirServ.py", line 42, in get_router
    self.retrieve_consensus()
  File "/root/pycepa/modules/Tor/DirServ.py", line 77, in retrieve_consensus
    request.register_local('chunk', self.chunk)
AttributeError: 'NoneType' object has no attribute 'register_local'
[root@i.broke.science:~/pycepa]# 
```
